.TH 2048 1
.SH NAME
2048 \- a clone of the game

.SH SYNOPSIS
2048

.SH DESCRIPTION
2048 is a minimal clone of the game 2048. It ignores it's arguments.
Shifting is done with "w" for "up", "a" for "left", "s" for "down"
and "d" for "right" (if not changed in the configuration), followed by
ENTER. Any arguments are ignored.

.SH BUGS
Not discovered yet. Many expected.

.SH AUTHOR
The best way to find me is at pranomestro@gmail.com (I didn't say that
it is a good way…).
