.Dd May 10, 2017
.Dt 2048 1
.Os

.Sh 2048
.Nm 2048
.Nd clone of the game

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
is a minimal clone of the game 2048.

.Sh OPTIONS
Command line arguments are ignored.
.Pp
Shifting the numbers is done with the following keys, followed by a newline:
.Bl -tag -width Ds
.It w
Shift the numbers up.
.It a
Shift the numbers left.
.It s
Shift the numbers down.
.It d
Shift the numbers right.

.Sh EXIT STATUS
.Ex -std

.Sh AUTHORS
.An pranomostro Aq Mt pranomestro@gmail.com
